export const GET_IMAGES = 'get-images'
export const SAVE_IMAGE = 'save-image'
export const REMOVE_SAVED_IMAGE = 'remove-saved-image'
export const GET_SIMILAR_IMAGES = 'get-similar-images'
export const CLEAR_SAVED_IMAGES = 'clear-saved-images'
